### ISSUE TITLE
Better styling for twisties

### ISSUE THREAD

**Issue by trailjeep** [trailjeep/dokuwiki-plugin-twistienav4bootstrap3#2]
Just some CSS to remove the distracting DW seperator characters and pad the glyphs/icons - twistie nav looks much slicker.

The commented item, additionally, removes the $lang['youarehere'] text at the beginning of the line.
```css
/* ol.breadcrumb > li:first-child  { display: none; } */
ol.breadcrumb > li + li::before { display: none; }
span.twistienav_twistie         { padding: 0 0.5em; }
```
